export enum TileType {
  Grass = "grass-tile",
  Water = "water-tile",
  Tree = "tree-tile",
  Iron = "iron-tile",
  Coal = "coal-tile",
  Stone = "stone-tile",
  Copper = "copper-tile",
  Lead = "lead-tile",
  BerryBush = "berry-bush-tile",
  Cave = "cave-tile",
  SulfurPool = "sulfur-pool-tile",
}

export enum TileRenderType {
  Grass1 = "grass-1-tile",
  Grass2 = "grass-2-tile",
  Grass3 = "grass-3-tile",
  Grass4 = "grass-4-tile",
  Grass5 = "grass-5-tile",
  Grass6 = "grass-6-tile",
  Grass7 = "grass-7-tile",
  Grass8 = "grass-8-tile",
  Grass9 = "grass-9-tile",
  Grass10 = "grass-10-tile",
  Grass11 = "grass-11-tile",
  Grass12 = "grass-12-tile",
  Grass13 = "grass-13-tile",
  Grass14 = "grass-14-tile",
  Grass15 = "grass-15-tile",
  Grass16 = "grass-16-tile",
  Grass17 = "grass-17-tile",
  Grass18 = "grass-18-tile",
  Grass19 = "grass-19-tile",
  Grass20 = "grass-20-tile",
  Grass21 = "grass-21-tile",
  Grass22 = "grass-22-tile",
  Grass23 = "grass-23-tile",
  Grass24 = "grass-24-tile",
  Grass25 = "grass-25-tile",
  Grass26 = "grass-26-tile",
  Grass27 = "grass-27-tile",
  Grass28 = "grass-28-tile",
  Grass29 = "grass-29-tile",
  Grass30 = "grass-30-tile",
  Grass31 = "grass-31-tile",
  Grass32 = "grass-32-tile",
  Water = "water-tile",
  Tree1 = "tree-1-tile",
  Tree2 = "tree-2-tile",
  Iron = "iron-tile",
  Coal = "coal-tile",
  Stone = "stone-tile",
  Copper = "copper-tile",
  Lead = "lead-tile",
  BerryBush = "berry-bush-tile",
  Cave = "cave-tile",
  SulfurPool = "sulfur-pool-tile",
}

export const tileData: Record<TileType, TileRenderType[]> = {
  [TileType.Grass]: [
    TileRenderType.Grass1,
    TileRenderType.Grass2,
    TileRenderType.Grass3,
    TileRenderType.Grass4,
    TileRenderType.Grass5,
    TileRenderType.Grass6,
    TileRenderType.Grass7,
    TileRenderType.Grass8,
    TileRenderType.Grass9,
    TileRenderType.Grass10,
    TileRenderType.Grass11,
    TileRenderType.Grass12,
    TileRenderType.Grass13,
    TileRenderType.Grass14,
    TileRenderType.Grass15,
    TileRenderType.Grass16,
    TileRenderType.Grass17,
    TileRenderType.Grass18,
    TileRenderType.Grass19,
    TileRenderType.Grass20,
    TileRenderType.Grass21,
    TileRenderType.Grass22,
    TileRenderType.Grass23,
    TileRenderType.Grass24,
    TileRenderType.Grass25,
    TileRenderType.Grass26,
    TileRenderType.Grass27,
    TileRenderType.Grass28,
    TileRenderType.Grass29,
    TileRenderType.Grass30,
    TileRenderType.Grass31,
    TileRenderType.Grass32,
  ],
  [TileType.Water]: [TileRenderType.Water],
  [TileType.Tree]: [TileRenderType.Tree1, TileRenderType.Tree2],
  [TileType.Iron]: [TileRenderType.Iron],
  [TileType.Coal]: [TileRenderType.Coal],
  [TileType.Stone]: [TileRenderType.Stone],
  [TileType.Copper]: [TileRenderType.Copper],
  [TileType.Lead]: [TileRenderType.Lead],
  [TileType.BerryBush]: [TileRenderType.BerryBush],
  [TileType.Cave]: [TileRenderType.Cave],
  [TileType.SulfurPool]: [TileRenderType.SulfurPool],
};
